export enum Command {
  Start = 'start',
  Help = 'help',
  Hosting = 'hosting',
  My = 'my',
  Add = 'add',
  Delete = 'delete',
  Ip = 'ip',
  Community = 'community',
  Free = 'free',
  Country = 'country',
  Company = 'company',
  Version = 'version',
  Stats = 'stats',
  Mode = 'mode',
  Ru = 'ru',
  En = 'en',
  Mirror = 'mirror',
  Locale = 'locale',
  Release = 'release',
  Admin = 'admin',
}
